### ISSUE TITLE
Connection fails if NTLM is configured

### ISSUE THREAD

**Issue by fahrenberger** [versionone/VersionOne.Integration.JIRA#11]
Apparently, when NTLM (Windows Integrated Authentication) is configured in a VersionOne instance, it is a bit more complicated to connect via REST API with an Application Token. But since version 15.1.0, it is possible, as pointed out here:
http://stackoverflow.com/questions/30973649/java-sdk-authentication-with-versionone-access-tokens

It is also included in the official documentation in the section "Connecting with Access Tokens":
https://community.versionone.com/VersionOne_Connect/Developer_Library/Get_an_SDK/Java_SDK/Creating_a_Connection

This of course means that the useOAuthEndpoints() method would have to be added to the V1Connector in your code as well.

We do need the NTLM authentication for convenience, and to get the JIRA integration working, we need this fix. The solution for you would probably be to add a checkbox "NTLM configured" in the V1 connection settings and add a remark to the error message thrown if the connection fails. You can then just include the useOAuthEndpoints() method in your V1Connector accordingly.

Let me know whether anybody is planning on doing this. I currently can't find the time...

**Comment by JogoShugh** [comment]
We resolved this in the last update. Thank you for pointing this out!
