### ISSUE TITLE
Migrate to JIRA REST API

### ISSUE THREAD

**Issue by ibuchanan** [versionone/VersionOne.Integration.JIRA#2]
[SOAP and XML-RPC will be removed in JIRA 7.0](https://developer.atlassian.com/display/JIRADEV/SOAP+and+XML-RPC+API+Deprecated+in+JIRA+6.0).

**Comment by jaymed** [comment]
Shouldn't this issue be closed now? Release 8.4 added support for the REST API.

**Comment by TerryDensmore** [comment]
Yes! 8.4 Did add REST support.
